name: Binaries

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.6.2", "9.4.6", "9.2.8", "8.10.7"]
        os: [ubuntu-latest, windows-latest]
        include:
          - ghc: "8.10.7"
            os: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.8.1.0

      - name: Set some window specific things
        if: matrix.os == 'windows-latest'
        run: echo 'EXE_EXT=.exe' >> $GITHUB_ENV

      - name: Configure project
        run: |
          cabal configure --enable-tests --enable-benchmarks --write-ghc-environment-files=ghc8.4.4+
          cabal build all --dry-run

      - name: Cabal cache over S3
        uses: action-works/cabal-cache-s3@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          region: us-west-2
          dist-dir: dist-newstyle
          store-path: ${{ steps.setup-haskell.outputs.cabal-store }}
          threads: 16
          archive-uri: ${{ secrets.BINARY_CACHE_URI }}
          skip: "${{ secrets.BINARY_CACHE_URI == '' }}"

      - name: Cabal cache over HTTPS
        uses: action-works/cabal-cache-s3@v1
        with:
          dist-dir: dist-newstyle
          store-path: ${{ steps.setup-haskell.outputs.cabal-store }}
          threads: 16
          archive-uri: https://cache.haskellworks.io/archive

      - name: Build
        # Try building it twice in case of flakey builds on Windows
        run: |
          cabal build all --enable-tests --enable-benchmarks --write-ghc-environment-files=ghc8.4.4+ || \
          cabal build all --enable-tests --enable-benchmarks --write-ghc-environment-files=ghc8.4.4+ -j1

      - name: Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BINARY_CACHE_URI: ${{ secrets.BINARY_CACHE_URI }}
        run: |
          cabal test all --enable-tests --enable-benchmarks --write-ghc-environment-files=ghc8.4.4+
